language: ruby
bundler_args: --without integration
rvm:
  - 2.0.0
  - 2.1.0
script: bundle exec rake travis
matrix:
  include:
  - rvm: 1.9.3
    language: ruby
    gemfile: Gemfile-1.9.3
    bundler_args: --without integration
